image: node
matrix:
  - env: SCRIPT=test NODE_VERSION=10

before_install:
  - nvm install node

install:
  - yarn install

script:
  - if [[ "$SCRIPT" ]]; then yarn $SCRIPT; fi

cache:
  - node_modules
